### ISSUE TITLE
why not indexeddb as default?

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#1]
IndexedDb is newer, and in use by more browsers, not sure why you would put websql as the default.

**Comment by haas85** [comment]
Hi,

I think that in most of the cases that HTML5 databases are used are in mobile webapps and they only support webSql tyhat was the reason, but maybe as you say it is better to set indexedDB as default (webSQL will be deprecated). 

Thank you

**Comment by haas85** [comment]
Finally I have changed it
