### ISSUE TITLE
Insert error

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#11]
You have "INSERT ,INTO" in your _insert method, resulting in the method always failing.

**Comment by haas85** [comment]
Ups !  It was an error I added to try if it returns the error correctly and I forgot to fix it. I will fix it later. Thanks!

**Comment by haas85** [comment]
Fixed! Thank you. If you like the project please give it a star if it doen't mind you. To make it to arrive to more people.

Thanks!

**Comment by ghost** [comment]
done, thanks for fast fix :)
