### ISSUE TITLE
SQL escape '

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#12]
_setValue should do this: 

```
        return "'" + (String(value).replace("'", "''")) + "'";
```

And ideally, it'd use prepared statement (websql).

**Comment by haas85** [comment]
I don't understand what do you mean with this. Can you explain better?

**Comment by ghost** [comment]
You don't escape the SQL properly. Even the above solution is not good. You should use prepared statements.

(websql)

```
 db.readTransaction(function (t) {
  t.executeSql('SELECT title, author FROM docs WHERE id=?', [id], function (t, data) {
    report(data.rows[0].title, data.rows[0].author);
  });
});
```

**Comment by haas85** [comment]
You mean not to return all the fields always?

**Comment by ghost** [comment]
I mean to escape quotes and stuff like that.. You do a simple_setValue for that but in reality you should use prepared statements. these do all the escapeing for you.

**Comment by ghost** [comment]
Any updates on this, it's quite important to escape!

**Comment by haas85** [comment]
I have been very bussy so it has been impossible for me do it now, because using prepared statements requires lots of changes. But if you need it asap you can make a branch and change that. This project is open source and you can do what you want with it :D

**Comment by haas85** [comment]
Finally I have added prepared statements :D. I know it has been a lot of time but I have no free time... I have made some trials and it worked for me, but I want to prepare some formal tests using jasmine
