### ISSUE TITLE
DB version

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#13]
You seem to save that in localStorage along with scheme, can I ask why? 

Anyway, you should at least do this: 

```
        VERSION_KEY += "_" + name;
    SCHEMA_KEY += "_" + name;
```

but if you can get rid of localStorage completely, that would be even better.

**Comment by haas85** [comment]
Using the localstorage is the only way to store the version of the database to be able to use the "autoversioning". In indexedDB a version change is needed for any schema change: add an objectStore, delete it or even create indexes, so it is necessary to use indexeddb in the easiest way. The schema is stored to search for changes and if there is a change in the schema upgrades the version.

**Comment by ghost** [comment]
Yes well why can't I just manually update the version number? Why do you have to save that for me. In any case, you need to add the name to the local storage keys in case a user has multiple databases on same domain.

**Comment by haas85** [comment]
You can also change the version manually. But think that this library is not only for working with indexedDB is to work with the supported database system without needing to duplicate your code if it is indexedDB or websql, so webDB needs a way to handle all the stuff in indexedDB as in websql and this was the only solution I was able to do.

I have just fixed what you say and it is available in the repository. Tanks!

**Comment by ghost** [comment]
websql doesn't care about version number anyway. And you should add name because i had multiple db's and it fucked it all up, version numbers from localstorage were used instead of the ones i set in the constructor.

**Comment by haas85** [comment]
As I said before it has been fixed. I know that websql doesn't about versions, but if you want to drop a table the function for indexedDB and for webSQL must be the same. Thats the reason why it was needed the autoversioning
