### ISSUE TITLE
4.95 mb size? 

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#2]
when I type 4.95 as the size, it pops up an alert in safari asking to create a database of 10mb.

**Comment by haas85** [comment]
All my trials were in chrome and firefox, maybe safari by default creates databases at least of 10 Mb.

**Comment by ghost** [comment]
No, when I set it to 4 (not 4.95) it worked correctly.

**Comment by haas85** [comment]
Ok, I will check this too, as I said is first version and there will appear more issues.

**Comment by haas85** [comment]
I have been trying this and it doesn't happened this to me. Sorry
