### ISSUE TITLE
error callbacks?

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#4]
what is the preferred method of catching errors?

**Comment by haas85** [comment]
By the moment if the return is null in callbacks, this is a first version, there are many thinks that can be improved.

**Comment by haas85** [comment]
Fixed, if you have worked with mongodb on node you will see a familiar callback structure (the callbacks will receive two parameters: error and result), read the new documentation, you will see the change. Sorry for the delay, but I have been too busy

**Comment by ghost** [comment]
Great work on all of the new features!
