### ISSUE TITLE
indexes?

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#5]
how does one add indexes to a table?

**Comment by haas85** [comment]
The first idea was to have same apis for webSQL and indexedDB, so by the moment the only way is to create them by accesing the database object.

**Comment by haas85** [comment]
You can access the DB instance in this way:
your_indexedDB_instance.db

in the future I will ad new features so this will be supported.

**Comment by ghost** [comment]
Would be really great to have this feature :) and cross compatible with websql too!
