### ISSUE TITLE
column type not respected

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#6]
Even though I have a text column defined, if all data in there appears to be numeric, you do not add quotes around the value, resulting in scientific notation of numbers (in case of very long ones), which is not what I want.

**Comment by ghost** [comment]
probably this can fix it: 

```
_setValue = function(value) {
  if (typeof(value) != "number") {
    return "'" + value + "'";
  } else {
    return value;
  }
};
```

**Comment by ghost** [comment]
Btw, what happens if there is a " in the value?

**Comment by ghost** [comment]
Should probably use this instead: 

http://stackoverflow.com/questions/10148599/prevent-sql-injection-in-websql-database-how-to-handle-quotes-in-data

**Comment by haas85** [comment]
You are right, I have been thinking about it for a long time. I have an idea of how to solve it.

Thank you for all the issues, on monday I will work on them ;)

**Comment by ghost** [comment]
ok great, and thank you for your work on this! much appreciated :)

**Comment by haas85** [comment]
Fixed, now the schema element's type is stored, read the new documentation, you will see many changes :D. Sorry for the delay, but I have been too busy

**Comment by ghost** [comment]
Thanks! One thing would be nice is if you looked up column type on update though - I had an id set as number and primary in the schema. But on update it was a string (from a hidden form field). The row did not update, until I did a parseInt().

**Comment by haas85** [comment]
I like the suggesestion. In the next version if the schema changes the table will also change.
