### ISSUE TITLE
indexeddb.open is not a function

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#7]
In chrome / firefox I get that error on this line:

```
  openRequest = indexedDB.open(name, version);
```

This is because that method is called from within a function called indexedDB

You should change it to 

window.indexedDB.open(name, version)

**Comment by haas85** [comment]
Fixed. Thanks!

If you want, please feel free to send me any pull request with improvements ;)

**Comment by ghost** [comment]
Thanks for your fast work on this :-)
