### ISSUE TITLE
keyPath should be extracted from schema

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#8]
In indexeddb, you always use "key" as the keyPath, however this leads to differences if I have "id" defined as the PRIMARY key in the schema between websql and indexeddb.

**Comment by haas85** [comment]
Key as keypath is to have an unique id that autoincrements as long as the user inserts registries. In webSql with webDB actually there is no way to define a primary key. I have been thinking about it, and on the next release there will be a way to add in both engines primary keys with autoinvrement.

**Comment by ghost** [comment]
Actually I have 

```
            id: "INTEGER PRIMARY KEY AUTOINCREMENT",
```

in my schema and this seems to work for Web SQL, but I guess you can't just parse that to extract necessary indexeddb info.

**Comment by haas85** [comment]
Fixed, in this version each table's schema can have a column defined with an object with primary attribute (this will make the column primary in webSQL and keypath in indexedDB ), and you can set it with autoincrement too, read the new documentation, you will see many changes :D. Sorry for the delay, but I have been too busy
