### ISSUE TITLE
select DISTINCT

### ISSUE THREAD

**Issue by ghost** [haas85/webdb#9]
just wondering, does indexedDB not support "select distinct column_name from table" sql statements? 

is there an alternative?

**Comment by ghost** [comment]
Oh nevermind, i now see that your 

```
indexedDB.prototype.execute = function(sql, callbacl) {
  return "";
};
```

simply returns ""

:-)

**Comment by ghost** [comment]
what's the alternative in doing this cross platform? just get all records and traverse over them in js? is there an indexeddb optimized way?

**Comment by haas85** [comment]
I have looked for a solution and I think that is the only way...
